"""empty message

Revision ID: 1b42e92e3a8c
Revises: 7a3783b21db0
Create Date: 2024-04-29 13:05:52.890750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b42e92e3a8c'
down_revision = '7a3783b21db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_column('cv_name')

    # ### end Alembic commands ###
