"""empty message

Revision ID: 44277f4658cc
Revises: 2a9199f39c43
Create Date: 2024-03-06 11:16:40.763146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44277f4658cc'
down_revision = '2a9199f39c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('courses')
    op.drop_table('professional_experience')
    op.drop_table('references')
    op.drop_table('languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name='languages_profile_id_fkey'),
    sa.PrimaryKeyConstraint('language_id', name='languages_pkey')
    )
    op.create_table('references',
    sa.Column('reference_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name='references_profile_id_fkey'),
    sa.PrimaryKeyConstraint('reference_id', name='references_pkey')
    )
    op.create_table('professional_experience',
    sa.Column('experience_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name='professional_experience_profile_id_fkey'),
    sa.PrimaryKeyConstraint('experience_id', name='professional_experience_pkey')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('institution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name='courses_profile_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', name='courses_pkey')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skill_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name='skills_profile_id_fkey'),
    sa.PrimaryKeyConstraint('skill_id', name='skills_pkey')
    )
    # ### end Alembic commands ###
