"""cv_email table added

Revision ID: 5e3ec09c0f2c
Revises: d2e1d65b1bee
Create Date: 2024-03-11 20:57:40.571900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3ec09c0f2c'
down_revision = 'd2e1d65b1bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('cv_email')

    # ### end Alembic commands ###
