"""empty message

Revision ID: 83cab03c4d02
Revises: 44277f4658cc
Create Date: 2024-03-06 11:17:13.564196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cab03c4d02'
down_revision = '44277f4658cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('course_title', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('language_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('professional_experience',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('employer', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('references',
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('skill_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('references')
    op.drop_table('professional_experience')
    op.drop_table('languages')
    op.drop_table('courses')
    # ### end Alembic commands ###
