"""Token revoking added user email

Revision ID: a4df5799b8cd
Revises: f26d5fd88682
Create Date: 2024-03-07 11:50:33.909226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4df5799b8cd'
down_revision = 'f26d5fd88682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('revoked_token_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('revoked_token_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
