"""Token revoking

Revision ID: f26d5fd88682
Revises: d1468f148210
Create Date: 2024-03-07 11:44:26.801985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26d5fd88682'
down_revision = 'd1468f148210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_constraint('basic_info_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_foreign_key('contact_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.create_foreign_key('basic_info_user_id_fkey', 'user', ['user_id'], ['id'])

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
